server {
    listen 80;
    listen [::]:80;

    # TODO (Task 7): set this to <Task 2>.<Task 3>
    # e.g. server_name vault.chucknorris.quest.local;
    server_name CHANGE_ME;

    # TODO (Task 7): set this to /var/www/web_page
    root CHANGE_ME;

    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}
