apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: default
spec:
  clusterIP: None
  selector:
    app: db-ss
  ports:
  - port: 5432
    name: postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-ss
  namespace: default
spec:
  serviceName: db-service
  replicas: 3
  selector:
    matchLabels:
      app: db-ss
  template:
    metadata:
      labels:
        app: db-ss
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: database
        image: postgres:15-alpine
        env:
        - name: POSTGRES_PASSWORD
          value: "SecretPassword123"
        ports:
        - containerPort: 5432
          name: postgres
