apiVersion: v1
kind: Secret
metadata:
  name: db-api-secret
  namespace: default
type: Opaque
stringData:
  api-key.txt: "super-secret-api-key-998877"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secure-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secure-service
  template:
    metadata:
      labels:
        app: secure-service
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
      containers:
      - name: app
        image: nginx:1.25-alpine
        command: ["/bin/sh", "-c", "echo 'Reading secret...'; cat /var/app/secrets/api-key.txt || exit 1; exec nginx -g 'daemon off;'"]
        ports:
        - containerPort: 80
        volumeMounts:
        - name: secret-volume
          mountPath: /var/app/secrets
      volumes:
      - name: secret-volume
        hostPath:
          path: /var/app/secrets-data
          type: DirectoryOrCreate
