apiVersion: apps/v1
kind: Deployment
metadata:
  name: ha-app
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ha-app
  template:
    metadata:
      labels:
        app: ha-app
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app: ha-app
      containers:
      - name: web-app
        image: nginx:1.25-alpine
        ports:
        - containerPort: 80
