apiVersion: batch/v1
kind: CronJob
metadata:
  name: data-backup-cron
  namespace: default
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Forbid
  suspend: true
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: busybox:1.36
            command: ["/bin/sh", "-c", "echo 'Backup completed successfully!'; exit 0"]
          restartPolicy: OnFailure
